### ISSUE TITLE
Unify and update licenses

### ISSUE THREAD

**Issue by comradekingu** [elementary/weblate#11]
https://l10n.elementary.io/accounts/profile/#licenses

These are all the licenses used:

GNU General Public License v2.0 only GPL-2.0
GNU General Public License v3.0 only GPL-3.0
GNU General Public License v3.0 or later GPL-3.0
GNU Lesser General Public License v2.1 only LGPL-2.1
GNU Lesser General Public License v3.0 only LGPL-3.0
Proprietary

It would be nice to move the "GPLv2/3-only" stuff to "GPLv3-or-later"
and "LGPL-2.1" to "LGPL-3.0" (or preferably GPLv3-or-later)

Also, the Website is "MIT" https://github.com/elementary/website/blob/master/LICENSE.md and should not be in proprietary.
I don't think anything should be in proprietary because it creates a mess https://github.com/elementary/store/issues/130

**Comment by ryonakano** [comment]
Fixed the license of the website and the store is shown as "Proprietary"

**Comment by lewisgoddard** [comment]
While we could updated LGPL 2.x to LGPL 3+, GPL licenses expressly forbid relicensing in this manner. We would likely (technically) require everyone who has contributed current code to GPL projects to allow the relicensing. I do not think this will be pursued, and if it is we won't co-ordinate in 'weblate'.

**Comment by comradekingu** [comment]
Now https://l10n.elementary.io/projects/icon-browser/#information proliferates the pool further with (the worst and most problematic license) CC0. Upstream is GPLv3.

@lewisgoddard 
Effectively stealing proprietary work to make it MIT (like above) is a far greater stretch than going from L/GPL-only into anything more copyleft.
You can copy all the translator e-mails from Weblate with the tool it has to list contributors.

To me this is an obvious and necessary effort, seeing as communicating 8 different licenses doesn't work for marketing, and I am pretty sure creates all sorts of technical problems too. (It really is 9, since all contributions taken before the change are still "proprietary".)

As far as unification goes, nothing should be "only".
There is no need for weak licenses, and GPL3 can go into AGPLv3 no problem.
There doesn't appear to be any rhyme or reason as to what kind of components are LGPL, so that whole license seems unwarranted.

As an example "Switchboard" is spread across
GNU General Public License v2.0 only
GNU General Public License v3.0 only
GNU Lesser General Public License v2.1 only and
GNU Lesser General Public License v3.0 only

That doesn't appear to be distributable at all.
GPL2 doesn't have a cure clause.
Sounds like something that comes back to bite everyone in the ass.

* Decide on a license (see above)
* Get all required code contributors onboard. (A lot of movement has already happened since I updated the licenses I could find that had a clear upgrade-path.)
* Change the licenses on Weblate,
* Drop translations that aren't re-licensed.
