### ISSUE TITLE
Comments disabled

### ISSUE THREAD

**Issue by comradekingu** [elementary/weblate#12]
But seemingly only for https://l10n.elementary.io/translate/terminal/terminal/en/?checksum=706bf35e99fb1870
Wanted to ask whether that is a noun or a verb.

**Comment by ryonakano** [comment]
Hi @comradekingu, can you still reproduce this issue? As far as I see the comments seems to be available for me:

![Screenshot from 2021-07-26 11-41-44](https://user-images.githubusercontent.com/26003928/126925895-127db8d3-0de2-46c8-a9be-eed2abd8237f.png)

> Wanted to ask whether that is a noun or a verb.

This is a label text shown in the context menu that triggers duplication of the currently shown terminal tab:

![2021-07-26 11 45 38 のスクリーンショット](https://user-images.githubusercontent.com/26003928/126926194-8e1b7685-a5f9-43b9-a343-d5167f493bc5.png)

**Comment by ryonakano** [comment]
Feel free to reopen if the issue persists.

**Comment by comradekingu** [comment]
@ryonakano The issue is I can't comment from English, because I only have access to nb_NO.
That is just Weblate being quirky, but next to nobody uses this restriction.
I don't see why everyone can't edit everything.
