### ISSUE TITLE
Can't start a new translation

### ISSUE THREAD

**Issue by elSolus** [elementary/weblate#14]
## What Happened

I considered translating the Calculator app and as my language wasn't there, I wanted to create a new translation but the button at the end saying "Start new translation" isn't clickable/tap-able.
(If possible I would like to be the one who started the translation in my language, instead of an admin created it for me and I just took from there.)

See the screenshot:
![Screenshot_2021-07-26-06-17-06-503_com brave browser](https://user-images.githubusercontent.com/77105020/126919630-4cb5b58c-5a11-41f3-b5d0-a2afa1dd53cf.jpg)

## Expected Behavior

I don't know, the next page the "Start a new translation" button is suppose to take me to.

## Steps to Reproduce

1. Open https://l10n.elementary.io/projects/calculator/calculator/
2. Go to the end and try "Start new translation"
3. The button is disabled

## Platform Information

Actually,
OS: MIUI 12.0.4 (Android)
Model: Redmi Note 10

**Comment by ryonakano** [comment]
Hi, thank you for your reporting. Adding new translation seems to be only permitted to administrators of our weblate. I'm a menber of them so I'll create a translation page of your language and give you a write access to it if you tell me which language you want to translate to.

Also, is your username on our weblate is "elSolus" which is the same with your GitHub username?

**Comment by elSolus** [comment]
Well, if it's only for the admins to create, please create one for Punjabi, India (Gurmukhi script). And yes, my username is the same on both platforms.

**Comment by ryonakano** [comment]
Thanks for your info. I just created elementary Punjab Translators which have a write access to the Punjab translations of all of our projects and added you to it. Also I created Punjab translations for Calculator so you should now be able to start translating it to Punjab.

If you find something wrong, let me know here or in the translators Slack. Thank you for your contribution to elementary OS!

**Comment by elSolus** [comment]
Hey, "Punjabi", man. 😂 Punjab is the region it's native to.
Thank you, btw.

Oh wait, @ryonakano why at the end, under "Translation file", it shows "po" along with "pa"? It should be "pa", "po" is not for Punjabi.

![IMG_20210726_110735](https://user-images.githubusercontent.com/77105020/126938643-0bed6a56-abf2-4db9-b9c1-847d8906c8bd.jpg)

**Comment by ryonakano** [comment]
Ah sorry for confusion! 😅

> Oh wait, @ryonakano why at the end, under "Translation file", it shows "po" along with "pa"? It should be "pa", "po" is not for Punjabi.

This represents where the translation files is in the project. We use GitHub to store the project and the Punjabi translation file is saved in a folder named `po` with the name `pa.po`:

https://github.com/elementary/calculator/blob/master/po/pa.po

And weblate just shows this. So don't worry, it's correct.

**Comment by elSolus** [comment]
Oh okay. Thanks for everything. 🙂
