### ISSUE TITLE
Add Punjabi translations

### ISSUE THREAD

**Issue by elSolus** [elementary/weblate#15]
## What Happened

Hey, @ryonakano 
APOLOGY:
First of all, sorry, but I couldn't find another way. I tried going to contributors profiles here and couldn't find any direct way to send a message.
REQUEST: Please add Punjabi translation file for (at least) the following apps:
AppCenter
Calendar
Browser
Website
And some other first-party ones. Thanks in advance.
And also tell me what is the best way to ask these types of questions/requests (new to github)?
Do any of you admins use Discord? Please send me the invite.

## Steps to Reproduce

1.
2.
3.

**Comment by ryonakano** [comment]
If you want to ask translation things, https://github.com/elementary/weblate would be a good place. Also we have a Slack workspace for those who translate elementary OS and I also join it, so if you interested in you can [join](https://join.slack.com/t/ele-l10n/shared_invite/zt-6afqz7ed-yyj4fsGHwwRX3XZq8Pdl~A).

I've already added Punjabi translation files for the following components:

- [x] AppCenter
- [x] Calendar
- [x] Camera
- [x] Initial Setup
- [x] Installer
- [x] Onboarding
- [x] Website
- [x] Store

And the browser (called Web or Epiphany) is a GNOME component. You can translate it in [Damned Lies](https://l10n.gnome.org/module/epiphany/).

**Comment by elSolus** [comment]
Thank you, @ryonakano . Any way to contact you more efficiently... I mean any Discord or other quick way?

**Comment by ryonakano** [comment]
Unfortunately I don't use Discord…

**Comment by ryonakano** [comment]
@elSolus Now Punjabi was added to [our website](https://elementary.io/pa/) too, so it would be great if you would work on these translations too.

Closing the issue since now all of our projects should have Punjabi translation files. Feel free to reopen/comment if something wrong or want to ask something for me!
