### ISSUE TITLE
Add stylesheet

### ISSUE THREAD

**Issue by ryonakano** [elementary/weblate#18]
### Problem

Stylesheet is ready for translation for [its repository structure](https://github.com/elementary/stylesheet/tree/master/po) but it's not added in our weblate, so they're not translated at all at the moment

### Proposal

It would be great if we add stylesheet to our weblate and contributors can translate them.

But this is blocked because of the following issues at the moment:

- [x] elementary/stylesheet#1104
- [x] elementary/stylesheet#1105

You can't see the strings in its appdata at the moment, so adding it to our weblate now has less meaning until these issues are resolved.

**Comment by danirabbit** [comment]
I've set up the weblate import, but I haven't figured out the other two issues quite yet. It's really strange! Working on it though.
Gonna close this since there's the other two issues to track the other things
