### ISSUE TITLE
Almost of all components has an alert

### ISSUE THREAD

**Issue by ryonakano** [elementary/weblate#2]
## What Happened

![Screenshot from 2021-01-17 10-34-47](https://user-images.githubusercontent.com/26003928/104828714-a5da4b80-58af-11eb-82d6-bd1843a00e0b.png)

![Screenshot from 2021-01-17 10-33-56](https://user-images.githubusercontent.com/26003928/104828710-99ee8980-58af-11eb-9cfe-bbb7204f89c4.png)

Almost of all components has an alert that says weblate cannot push the repository. This means the translations added by translators are not pushed to repositories maybe?

## Expected Behavior

There should not be such an alert and translations should be always pushed to repositories.

## Steps to Reproduce

1. Visit https://l10n.elementary.io/
2. See almost of all components have the alert mark (:exclamation:)

## Platform Information

* elementary Weblate 4.4

**Comment by imgradeone** [comment]
https://twitter.com/elementary/status/1348322329135177729?s=20
see here for some info

**Comment by btkostner** [comment]
The translation issue has been fixed and all components are now unlocked. There is one remaining "alert" open in weblate that I filed an issue about. 

https://github.com/elementary/weblate/issues/3

Let me know if things are not working as intended.

**Comment by ryonakano** [comment]
@btkostner Thank you for your work! I also confirmed all components are unlocked. However, there still seems to be a "could not push the repository" warning besides the alert about ambiguous language code:

<img width="432" alt="スクリーンショット 2021-01-18 16 52 51" src="https://user-images.githubusercontent.com/26003928/104886889-cd174280-59ad-11eb-99b8-d4d0a4dc9333.png">

Would you take a look at it?

**Comment by btkostner** [comment]
That alert should have been from before I fixed it. I'm not sure I can delete the old alerts, but you shouldn't have to worry about them.

**Comment by ryonakano** [comment]
Ah, now this alert seems to have gone. I may have visited the weblate while the fix is in progress.
