### ISSUE TITLE
Upgrade weblate to a newer version

### ISSUE THREAD

**Issue by ryonakano** [elementary/weblate#21]
### What Happened?

We use Weblate 4.4.2 which is [released](https://github.com/WeblateOrg/weblate/releases/tag/weblate-4.4.2) over than one years before. And it says we should upgrade to newer version:

![screen](https://user-images.githubusercontent.com/26003928/185729821-36baadff-78fe-40e7-a36a-ec3c95b69143.png)

### Steps to Reproduce

1. Sign in to weblate with admin right
2. Open the [Performance report](https://l10n.elementary.io/manage/performance/) page
3. See the message

### Expected Behavior

We should upgrade weblate to a newer version.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

N/A

**Comment by davidmhewitt** [comment]
This is complete
