### ISSUE TITLE
Update the Italian translation

### ISSUE THREAD

**Issue by Odi-3** [elementary/weblate#22]
### Problem

The Italian translation hasn't been updated for a long time and every part of the operating system has lost its linguistic coherence.

### Proposal

I'm working on Weblate so that I can provide all the necessary suggestions, but it needs someone to update the Italian translation and check it regularly.

**Comment by danirabbit** [comment]
Hey, thanks for your interest in getting involved here! If you could join the Matrix chat a localization team admin will be able to help you. Check out our contributor documentation for more info here: https://docs.elementary.io/contributor-guide/localization/translations
