### ISSUE TITLE
en_US is now set as default language

### ISSUE THREAD

**Issue by tintou** [elementary/weblate#4]
en_US (written in the UI as `English (United Stated)`) is now the default language when it used to be simply `en`
This leads to the `en` language being now a thing. Our standard English language is the one from the US so we don't need en_US in elementary.
In practice, it means that weblate adds the `en` locale to all the LINGUAS files which then makes our software fail to build

**Comment by btkostner** [comment]
Should be fixed in weblate now. I can maybe try a weblate push to all repos to fix the build then? I'm not sure if you guys want that.

**Comment by danirabbit** [comment]
It doesn't look like Weblate will remove Lang codes so I'm going through and updating the LINGUAS files manually. This can probably be closed
