### ISSUE TITLE
Portuguese(pt) translation

### ISSUE THREAD

**Issue by hugok79** [elementary/weblate#5]
I am the Portuguese translator, my nickname at Weblate is (@hugok) and have always kept elementary 100% translated. So far I have done 4,812 translations for this project. But what I wanted to highlight here is that Portuguese is a very complete language and it is spoken in several countries such as Brazil, Angola, Mozambique, East Timor among others. As such there are some differences in the way of speaking and writing among these countries, especially in Brazil. So I was going to ask that whenever someone asks to have permissions to save translations in Weblate, that they pay attention to the language code, because Portuguese is (pt) and Brazilian Portuguese is (pt_BR). I have seen many suggestions by Brazilians in the translation of the Portuguese which is not correct. I have maintained the Portuguese translation with quality and adapted to Portuguese users (Portugal) and as such I would not like to see Brazilians messing up that same translation.

I hope there is some control of who is responsible for adding translators so that the translations and the work of those who do them are not harmed.

Your beloved Portuguese(pt) translation contributor,

Hugo Carvalho aka hugok

**Comment by tintou** [comment]
Olá Hugo!
First thanks for you work on the translation!
The `pt` and `pt_BR` teams aren't the same currently in Weblate and a member of `pt_BR` shouldn't be able to save things to `pt`
Have you seen a case where a `pt_BR` user has saved a translation in `pt` or is that only suggestions?

**Comment by hugok79** [comment]
Olá Corentin 👍🏻
No, I don't think I have seen a translation yet been saved by a “pt_BR” user, only suggestions. How many “pt” users have the permission to save translations besides me?
