### ISSUE TITLE
Texts are not translated consistently

### ISSUE THREAD

**Issue by meisenzahl** [elementary/weblate#9]
## What Happened

I just noticed that certain texts are not translated consistently across projects. I have summarized this here below once for the accent colors in German as an example.

| English | German (`io.elementary.onboarding`) | German (`switchboard-plug-pantheon-shell`) | German (https://elementary.io/de/brand) |
| --- | --- | --- | --- |
| Blueberry | Heidelbeere | Blaubeere | Heidelbeer |
| Mint | Minze | Mintgrün | Mint |
| Lime | Gelbgrün | Lindgrün | Limette |
| Banana | Banane |  Banane | Banane |
| Orange | Orange | Orange | Orange |
| Strawberry | Erdbeere | Erdbeere | Erdbeere |
| Pink | Rosa | Rosa | Bubblegum |
| Grape | Weinrot | Violett | Weintraube |
| Cocoa | Kakao | Kakao | Kakao |
| Slate | Schiefer | Schiefer | Schiefer |

## Expected Behavior

I would expect that especially such prominent texts would be translated consistently.

## Steps to Reproduce

1. Change your language to German
2. Run `io.elementary.onboarding`
3. Run `switchboard-plug-pantheon-shell`
4. Open https://elementary.io/de/brand in your browser

## Idea

Is it possible to link exactly the same texts across projects in Weblate so that they only need to be translated once?

**Comment by tintou** [comment]
It is not possible to do it, you can make it easier though by:
 * translating all the occurrences for good by using the right query (ex: https://l10n.elementary.io/search/?offset=1&q=+source%3ABlueberry++is%3Atranslated+AND+language%3Ade&sort_by=-priority%2Cposition&checksum= )
 * using a German glossary that checks that the right translation is used and suggested to new strings (though Glossary support has been massively improved with Weblate 4.5)

**Comment by meisenzahl** [comment]
Thanks for the explanation! I have suggested the translations in Weblate consistently.

I have not worked with Weblate before. @ryonakano do you have any idea who I need to contact from the German translators so we can consistently translate the texts?

**Comment by ryonakano** [comment]
@ryonakano I added you to the German Translators group in weblate, so you should be able to approve suggestions you added.

**Comment by ryonakano** [comment]
@meisenzahl I added you to the German Translators group in weblate, so you should be able to approve suggestions you added.
